import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { Sign } from "crypto";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {

  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return (
    <div className="flex gap-3 w-full">
      <Image 
        src={user.imageUrl}
        alt="Profile image"
        className="h-16 w-16 rounded-full"
        width={56}
        height={56}
      />
      <input placeholder="type some emojis!" 
      className="grow bg-transparent outline-none text-orange-800"/>
    </div>
  );
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const {post, author} = props;
  return (
    <div key ={post.id} className="border-b border-black p-4 flex gap-3 ">
      <Image 
        //imageUrl and user icon not working on posts
        src={author.profilePictureUrl}
        alt={`@${author.username} profile image`}
        className="h-16 w-16 rounded-full"
        width={56}
        height={56}
        />
        <div className="flex flex-col">
          <div className="flex text-orange-900 gap-2 font-semibold">
            <span>
              {`@${author.username}`}
            </span>
            <span className="font-extralight">
              {`  .  ${dayjs(post.createdAt).fromNow()}`}
            </span>
          </div>
          <span>{post.content}</span>
        </div>
    </div>
  );
};

const Home: NextPage = () => {

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className= " bg-orange-300/70 border-black w-full h-full border-x md:max-w-2xl">
          <div className = "border-b border-black p-4 flex">
            {!user.isSignedIn && (
            <div className = "flex justify-center">
              <SignInButton />
            </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className = "flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))};
          </div>
        </div>
      </main>
    </>
  );
};
export default Home;